[package]
name = "econf"
version = "0.1.3"
authors = ["Yushi OMOTE <yushiomote@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Load environment variables into your struct members directly."
homepage = "https://github.com/YushiOMOTE/econf"
documentation = "https://docs.rs/econf"
repository = "https://github.com/YushiOMOTE/econf"

[dependencies]
log = "0.4"
serde = "1.0"
serde_yaml = "0.8"
econf-derive = { version = "0.1.3", path = "../econf-derive" }
parse_duration = "1.0"

[dev-dependencies]
simple_logger = "0.5"
