[package]
name = "econf"
version = "0.1.2"
authors = ["Yushi OMOTE <yushiomote@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Load environment variables into your struct members directly."

[dependencies]
log = "0.4"
serde = "1.0"
serde_yaml = "0.8"
econf-derive = { version = "0.1.2", path = "../econf-derive" }
parse_duration = "1.0"

[dev-dependencies]
simple_logger = "0.5"
